version: '3'
services:
    postgresql-database-service:
        image: postgres:14
        container_name: postgresql-database-service
        environment:
        - POSTGRES_USER=astro
        - POSTGRES_PASSWORD=astro
        - POSTGRES_DB=astro
        ports:
        - "5432:5432"
