# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java/Kotlin CI with Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@c295a4096e1d2c453eaf1f65c6f96686e26bd8be
      with:
        arguments:  build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
    - name: Upload native executable
      uses: actions/upload-artifact@v2
      with:
        name: native-executable
        path: build/*-runner
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Dockerized App
      uses: docker/build-push-action@v2
      with:
          context: apps/web/src/main/docker
          file: ./Dockerfile.native
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}
