on: [push]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Build native executable
        uses: maxday/quarkus-native-build-docker-action
        with:
          outputName: app-runner
          dockerfilePath: apps/web/src/main/docker/Dockerfile.native
      - name: Upload native executable
        uses: actions/upload-artifact@v1
        with:
          name: native-executable
          path: app-runner

  dockerize:
    runs-on: ubuntu-latest
    name: Embed the native executable in a Docker container
    needs: native_build
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Download the binary
        uses: actions/download-artifact@v1
        with:
          name: native-executable
      - name: Dockerize
        id: dockerize
        uses: maxday/quarkus-dockerize-action@master
        with:
          tag: n4t5u/quarkus-astro-starter
          executablePath: native-executable/app-runner
